version: 2

models:
  # - name: dm_daily_biometrics
  #   description: 
  #   columns:
    
  - name: fact_daily_summary
    description: >
        aggregate sleep, heartrate, and profile data into a single daily summary per user
    columns:
      - name: user_id
        data_type: string
        description: "The unique identifier for the user."
      - name: date
        data_type: timestamp
        description: "The date of the recorded metrics."
      - name: age
        data_type: integer
        description: "The age of the user based on their specified birthday."
      - name: gender
        data_type: string
        description: "The user's specified gender. Supported values: MALE, FEMALE, NA."
      - name: height
        data_type: float
        description: "The height of the user as specified in their account settings."
      - name: weight
        data_type: float
        description: "The current weight of the user as specified in their account settings."
      - name: distance_unit
        data_type: string
        description: "The unit system defined in the user's account settings for distance."
      - name: duration
        data_type: integer
        description: "The duration of the sleep in milliseconds."
      - name: efficiency
        data_type: float
        description: "The calculated sleep efficiency score."
      - name: minutes_awake
        data_type: integer
        description: "The total number of minutes the user was awake during the sleep period."
      - name: minutes_to_fall_asleep
        data_type: integer
        description: "The total number of minutes it took for the user to fall asleep."
      - name: time_in_bed
        data_type: integer
        description: "The total number of minutes the user was in bed."
      - name: deep_minutes
        data_type: integer
        description: "The total number of minutes the user spent in deep sleep."
      - name: light_minutes
        data_type: integer
        description: "The total number of minutes the user spent in light sleep."
      - name: rem_minutes
        data_type: integer
        description: "The total number of minutes the user spent in REM sleep."
      - name: wake_minutes
        data_type: integer
        description: "The total number of minutes the user was awake during the sleep period."
      - name: zone1_calories_out
        data_type: float
        description: "The number of calories burned in heart rate zone 1."
      - name: zone1_max_heartrate
        data_type: integer
        description: "The maximum heart rate in heart rate zone 1."
      - name: zone1_min_heartrate
        data_type: integer
        description: "The minimum heart rate in heart rate zone 1."
      - name: zone1_minutes
        data_type: integer
        description: "The number of minutes spent in heart rate zone 1."
      - name: zone2_calories_out
        data_type: float
        description: "The number of calories burned in heart rate zone 2."
      - name: zone2_max_heartrate
        data_type: integer
        description: "The maximum heart rate in heart rate zone 2."
      - name: zone2_min_heartrate
        data_type: integer
        description: "The minimum heart rate in heart rate zone 2."
      - name: zone2_minutes
        data_type: integer
        description: "The number of minutes spent in heart rate zone 2."
      - name: zone3_calories_out
        data_type: float
        description: "The number of calories burned in heart rate zone 3."
      - name: zone3_max_heartrate
        data_type: integer
        description: "The maximum heart rate in heart rate zone 3."
      - name: zone3_min_heartrate
        data_type: integer
        description: "The minimum heart rate in heart rate zone 3."
      - name: zone3_minutes
        data_type: integer
        description: "The number of minutes spent in heart rate zone 3."
      - name: zone4_calories_out
        data_type: float
        description: "The number of calories burned in heart rate zone 4."
      - name: zone4_max_heartrate
        data_type: integer
        description: "The maximum heart rate in heart rate zone 4."
      - name: zone4_min_heartrate
        data_type: integer
        description: "The minimum heart rate in heart rate zone 4."
      - name: zone4_minutes
        data_type: integer
        description: "The number of minutes spent in heart rate zone 4."
      - name: resting_heart_rate
        data_type: integer
        description: "The user's resting heart rate."