version: 2

models:
  # - name: dm_daily_biometrics
  #   description: 
  #   columns:

  - name: fact_medications_time_cost_loc
    description: >
        Comprehensive fact table combining medications data with patient demographics, encounter details, and organization information for analytics
    columns: 
      # MEDICATIONS
      - name: medication_id
        data_type: string
        description: "Unique identifier for each medication record (generated surrogate key)"
      - name: medication_code
        data_type: string
        description: "Medication code from RxNorm"
      - name: medication_description
        data_type: string
        description: "Description of the medication"
      - name: reason_code
        data_type: string
        description: "Diagnosis code from SNOMED-CT specifying why this medication was prescribed"
      - name: reason_description
        data_type: string
        description: "Description of the reason code"
      - name: start_timestamp
        data_type: timestamp
        description: "The date and time the medication was prescribed"
      - name: stop_timestamp
        data_type: timestamp
        description: "The date and time the prescription ended, if applicable"
      - name: dispenses
        data_type: integer
        description: "The number of times the prescription was filled"
      - name: base_cost
        data_type: float
        description: "The line item cost of the medication"
      - name: payer_coverage
        data_type: float
        description: "The amount covered or reimbursed by the Payer"
      - name: total_cost
        data_type: float
        description: "The total cost of the prescription, including all dispenses"

      # PATIENTS
      - name: patient_id
        data_type: string
        description: "Primary Key. Unique Identifier of the patient."
      - name: birth_date
        data_type: date
        description: "The date the patient was born."
      - name: death_date
        data_type: date
        description: "The date the patient died."
      - name: marital_status
        data_type: string
        description: "Marital Status. M is married, S is single. Currently no support for divorce (D) or widowing (W)"
      - name: race
        data_type: string
        description: "Description of the patient's primary race."
      - name: ethnicity
        data_type: string
        description: "Description of the patient's primary ethnicity."
      - name: gender
        data_type: string
        description: "Gender. M is male, F is female."
      - name: birthplace
        data_type: string
        description: "Name of the town where the patient was born."
      - name: address
        data_type: string
        description: "Patient's street address without commas or newlines."
      - name: city
        data_type: string
        description: "Patient's address city."
      - name: state
        data_type: string
        description: "Patient's address state."
      - name: county
        data_type: string
        description: "Patient's address county."
      - name: fips_code
        data_type: string
        description: "Patient's FIPS county code."
      - name: zip_code
        data_type: string
        description: "Patient's zip code."
      - name: latitude
        data_type: float
        description: "Latitude of Patient's address."
      - name: longitude
        data_type: float
        description: "Longitude of Patient's address."
      - name: healthcare_expenses
        data_type: float
        description: "The total lifetime cost of healthcare to the patient (i.e. what the patient paid)."
      - name: healthcare_coverage
        data_type: float
        description: "The total lifetime cost of healthcare services that were covered by Payers (i.e. what the insurance company paid)."
      - name: income
        data_type: float
        description: "Annual income for the Patient"

      # ENCOUNTERS
      - name: encounter_id
        data_type: string
        description: "Primary Key. Unique Identifier of the encounter"
      - name: encounter_class
        data_type: string
        description: "The class of the encounter, such as ambulatory, emergency, inpatient, wellness, or urgentcare"
      - name: encounter_code
        data_type: string
        description: "Encounter code from SNOMED-CT"
      - name: encounter_description
        data_type: string
        description: "Description of the type of encounter"
      - name: encounter_reason_code
        data_type: string
        description: "Diagnosis code from SNOMED-CT specifying why this encounter occurred"
      - name: encounter_reason_description
        data_type: string
        description: "Description of the encounter reason code"
      - name: encounter_start_timestamp
        data_type: timestamp
        description: "The date and time the encounter started"
      - name: encounter_stop_timestamp
        data_type: timestamp
        description: "The date and time the encounter ended"
      - name: base_encounter_cost
        data_type: float
        description: "The base cost of the encounter, not including any line item costs related to medications, immunizations, procedures, or other services"
      - name: total_claim_cost
        data_type: float
        description: "The total cost of the encounter, including all line items"
      - name: encounter_payer_coverage
        data_type: float
        description: "The amount covered or reimbursed by the Payer for the encounter"

      # ORGANIZATIONS
      - name: organization_id
        data_type: string
        description: "Primary key of the Organization."
      - name: organization_name
        data_type: string
        description: "Name of the Organization."
      - name: organization_address
        data_type: string
        description: "Organization's street address without commas or newlines."
      - name: organization_city
        data_type: string
        description: "Organization's address city."
      - name: organization_state
        data_type: string
        description: "Organization's address state."
      - name: organization_zip_code
        data_type: string
        description: "Organization's zip code."
      - name: phone
        data_type: string
        description: "Organization's phone number. Sometimes multiple numbers."
      - name: organization_latitude
        data_type: float
        description: "Latitude of Organization's address."
      - name: organization_longitude
        data_type: float
        description: "Longitude of Organization's address."
      - name: revenue
        data_type: float
        description: "The monetary revenue of the organization during the entire simulation."
      - name: utilization
        data_type: integer
        description: "The number of Encounters performed by this Organization."
